### ISSUE TITLE
How to test server module ?

### ISSUE THREAD

**Issue by Posterone** [ibaca/autorest-nominatim-example#2]
Hi @ibaca, I have tested gwt module and it is working with "http://nominatim.openstreetmap.org/" but I wanted to test server module as well. I thought that starting the server, and changing the path in gwt module from "http://nominatim.openstreetmap.org/" to ""http://127.0.0.1:8080/"" should be enough to get the results from server module instead of openstreetmap ?

When I start server and gwt module I receive the following error in server module console each time I refresh the browser (each time gwt module tries to call server module):

com.sun.jersey.server.wadl.generators.AbstractWadlGeneratorGrammarGenerator attachTypes
INFO: Couldn't find grammar element for class rx.Observable

Am I missing something or I misunderstood the role of server module ?

Thanks in advance.

**Comment by ibaca** [comment]
Uhm... this is a pretty weird error, not sure why you get that. But, I have just updated the project so it makes more sense to integrate GWT client with the Jetty Jersey Server. Now when the server receives a request, it makes another request to the actual OpenStreetMap server using the JRE implementation, so the server act as a proxy but using the JAX-RS Nominatim interface as server and client at the same time. Also, I had added CORS filter to the server because right now, if you try to use the client in devmode (so http://localhost:8888/example/) and the server (http://localhost:8080/) you'll get a CORS error if you don't add the headers. Anyway, to confirm that the server works just run it (easier using your IDE and just running the Server.main) and open http://localhost:8080/search?format=json&q=m%C3%A1laga to confirm it works.

Finally, the client has been updated so you can choose the server and search text to try it out easier.

Try it again, I hope it works! 😛

**Comment by Posterone** [comment]
It's working great! Thank you.
